# global:
#   resolve_timeout: 2m

# route:
#   receiver: 'telegram'
#   group_wait: 15s
#   group_interval: 1m
#   repeat_interval: 2m

# receivers:
#   - name: 'telegram'
#     telegram_configs:
#       - bot_token: '7845756482:AAHXL9m8iTwOSvAgeiY67PmuvjmOYI8xDBQ'
#         chat_id: -1943348585
#         send_resolved: true
#         message: |
#           🚨 *Cảnh báo Prometheus* 🚨
#           *Tên cảnh báo:* {{ .CommonLabels.alertname }}
#           *Mức độ:* {{ .CommonLabels.severity }}
#           *Máy chủ:* {{ .CommonLabels.instance }}
#           *Mô tả:* {{ .CommonAnnotations.description }}

# # templates:
# # - templates/telegram.tmpl
