groups:
  - name: memory_alerts
    rules:
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Cảnh báo sử dụng bộ nhớ cao"
          description: "Sử dụng RAM vượt quá 90% trong hơn 2 phút."
